### PR TITLE
Perf

### PR DESCRIPTION
**Pull request by matl33t**
First attempt at increasing performance (https://github.com/matl33t/apa102_rbpi/issues/11)
I primarily reduced a few method calls and unneeded object creation for non-mirrored strips using `set_pixel`.

Using the added benchmark script, I got these numbers:

BEFORE

```
Running benchmark for single strip...
Mean running time: 0.6749723666666667
Standard Deviation: 0.018963434894524008
Running benchmark for mirrored strips...
Mean running time: 0.41152513333333346
Standard Deviation: 0.018560515398115377
```

AFTER

```
Running benchmark for single strip...
Mean running time: 0.10346416666666669
Standard Deviation: 0.00738851433007659
Running benchmark for mirrored strips...
Mean running time: 0.44753513333333333
Standard Deviation: 0.021446812514126477
```

I did an initial attempt at using some inline C, but did not get much more improvement. May have to look into using an actual C extension to handle framedata for any noticeable benefit.

### CODE REVIEW

**Comment by matl33t** [comment]
@estiens I pushed a prerelease version `1.1.pre` if you'd like to give this a try.

**Comment by estiens** [comment]
Looks like a great easy win! Performance improvements look grand. 

Here's a tiny video of the installation that used this library if you are interested. It was driving 20 meters of Adafruit Dotstar 30 pixels/meter strips, so about 600 LEDs.

https://cl.ly/0d3k3H420P0S

**Comment by matl33t** [comment]
Wow! Really love that infinity mirror effect you have going there. Took a peek at your code - looking forward to seeing that on the playa 😀

**Comment by estiens** [comment]
Code is kinda trash at the moment, had one weekend to get some nice patterns working, but it will get cleaned up! Thanks again for the library.

**Comment by matl33t** [comment]
Was able to improve the mirrored strip performance as well:

```
Running benchmark for single strip...
Mean running time: 0.10462809999999999
Standard Deviation: 0.008259084942843454
Running benchmark for mirrored strips...
Mean running time: 0.1211389
Standard Deviation: 0.00971391294200373
```

This came at the cost of having `strip.mirrors` writable. I saw somewhere in your code you were using `strip.mirrors.clear`, so I made a `strip.clear_mirrors` method you can use to not break functionality.

**Pull request merged**
